// Default status column labels
export const DEFAULT_STATUS_LABELS: Record<
  string,
  { label: string; color: string }
> = {
  not_started: { label: "Not Started", color: "#C4C4C4" },
  working: { label: "Working on it", color: "#FDAB3D" },
  stuck: { label: "Stuck", color: "#E2445C" },
  done: { label: "Done", color: "#00C875" },
};

// Default group colors
export const GROUP_COLORS = [
  "#579BFC", // Blue
  "#00C875", // Green
  "#FDAB3D", // Orange
  "#E2445C", // Red
  "#A25DDC", // Purple
  "#037F4C", // Dark Green
  "#CAB641", // Yellow
  "#66CCFF", // Light Blue
  "#FF642E", // Coral
  "#7F5347", // Brown
];

// Column type display metadata
export const COLUMN_TYPE_META: Record<
  string,
  { label: string; icon: string; description: string }
> = {
  text: { label: "Text", icon: "type", description: "Free text field" },
  number: { label: "Number", icon: "hash", description: "Numeric value" },
  status: { label: "Status", icon: "circle-dot", description: "Status labels with colors" },
  person: { label: "Person", icon: "user", description: "Assign team members" },
  date: { label: "Date", icon: "calendar", description: "Date picker" },
  timeline: { label: "Timeline", icon: "calendar-range", description: "Date range" },
  checkbox: { label: "Checkbox", icon: "check-square", description: "True/false toggle" },
  link: { label: "Link", icon: "link", description: "URL" },
  file: { label: "File", icon: "paperclip", description: "File attachment" },
  formula: { label: "Formula", icon: "function-square", description: "Computed value" },
  ai_generated: { label: "AI Generated", icon: "sparkles", description: "Value generated by AI based on other columns" },
  dropdown: { label: "Dropdown", icon: "chevron-down", description: "Single select from options" },
  rating: { label: "Rating", icon: "star", description: "Star rating (1-5)" },
  tags: { label: "Tags", icon: "tags", description: "Multiple labels" },
  email: { label: "Email", icon: "mail", description: "Email address" },
  phone: { label: "Phone", icon: "phone", description: "Phone number" },
  location: { label: "Location", icon: "map-pin", description: "Geographic location" },
  dependency: { label: "Dependency", icon: "git-branch", description: "Link to dependent items" },
};

// API limits
export const MAX_ITEMS_PER_PAGE = 100;
export const MAX_COLUMNS_PER_BOARD = 100;
export const MAX_GROUPS_PER_BOARD = 50;
export const MAX_AGENT_ACTIONS_PER_RUN = 100;
